/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 desk.glb -T 
Files: desk.glb [517.1KB] > /Users/hsuwinlatt/Desktop/Work/jsm pj/three-d-portfolio-2025/public/models/desk-transformed.glb [38.99KB] (92%)
Author: Nyangire (https://sketchfab.com/Nyangire)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-computer-desk-646ed84ecd9d40089c31d94f79334ca5
Title: Low Poly Computer Desk
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Desk(props) {
  const { nodes, materials } = useGLTF("/models/desk-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.KeyboardCable_ComputerDesk_0.geometry}
        material={materials.ComputerDesk}
        position={[34.329, 76.164, 56.062]}
      />
      <mesh
        geometry={nodes.Floppy_disk_FloppyDisk_0.geometry}
        material={materials.FloppyDisk}
        position={[-41.906, 74.815, 65.87]}
        rotation={[Math.PI / 2, 0, 0.247]}
      />
    </group>
  );
}

useGLTF.preload("/models/desk-transformed.glb");
