/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 git-svg.glb -T 
Files: git-svg.glb [505.72KB] > /Users/hsuwinlatt/Desktop/Work/jsm pj/three-d-portfolio-2025/public/models/git-svg-transformed.glb [15.82KB] (97%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function GitLogo(props) {
  const { nodes } = useGLTF("/models/git-svg-transformed.glb");
  return (
    <group scale={0.05} {...props} dispose={null}>
      <mesh
        geometry={nodes.mesh_0.geometry}
        material={nodes.mesh_0.material}
        position={[-37.233, 50.062, 33.39]}
        rotation={[0, Math.PI / 4, -Math.PI]}
        scale={[-1.087, 1.087, 1.087]}
      />
    </group>
  );
}

useGLTF.preload("/models/git-svg-transformed.glb");
