/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 guy.glb -T 
Files: guy.glb [3.41MB] > /Users/hsuwinlatt/Desktop/Work/jsm pj/three-d-portfolio-2025/public/models/guy-transformed.glb [403.09KB] (88%)
Author: klava88 (https://sketchfab.com/klava88)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-guy-is-like-robocop-animated-0f64bad78a8847fbbe751c5aae4f83d1
Title: The guy is like Robocop (Animated)
*/

import React, { useEffect } from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Guy(props) {
  const group = React.useRef();
  const { scene, animations } = useGLTF("/models/guy-transformed.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    actions["mixamo.com"]?.play();
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh
          name="Object_7"
          geometry={nodes.Object_7.geometry}
          material={materials["Material.001"]}
          skeleton={nodes.Object_7.skeleton}
          scale={0.015}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/guy-transformed.glb");
