/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 laptop.glb -T 
Files: laptop.glb [4.71MB] > /Users/hsuwinlatt/Desktop/Work/jsm pj/three-d-portfolio-2025/public/models/laptop-transformed.glb [257.06KB] (95%)
Author: timblewee (https://sketchfab.com/timblewee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-pro-13-inch-2020-efab224280fd4c3993c808107f7c0b38
Title: Macbook Pro 13 inch 2020
*/

import React, { useEffect } from "react";
import { useGLTF, useAnimations, useTexture } from "@react-three/drei";

export function Laptop(props) {
  const group = React.useRef();
  const { nodes, materials, animations, scene } = useGLTF(
    "/models/laptop-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);
  const screen = useTexture("/images/project2.png");

  useEffect(() => {
    // console.log(actions);

    scene.traverse((child) => {
      if (child.isMesh && child.name === "Object_7") {
        child.material.map = screen;
      }
    });

    actions["Animation"]?.play();
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="GLTF_SceneRootNode">
          <group name="Bevels_2" position={[0, 0.008, -0.104]} scale={0.275}>
            <group
              name="Empty_1"
              position={[0, 0.001, 0]}
              rotation={[-Math.PI, 0, 0]}
              scale={[-0.039, 0.039, 0.039]}
            >
              <group
                name="Camera_Light_0"
                position={[0, 0.077, -0.044]}
                rotation={[-1.192, 0, 0]}
                scale={[-25.381, 25.381, 25.381]}
              >
                <mesh
                  name="Object_12"
                  geometry={nodes.Object_12.geometry}
                  material={materials.PaletteMaterial003}
                />
              </group>
            </group>
            <mesh
              name="Object_4"
              geometry={nodes.Object_4.geometry}
              material={materials.PaletteMaterial001}
            />
            <mesh
              name="Object_6"
              geometry={nodes.Object_6.geometry}
              material={materials.PaletteMaterial002}
            />
            <mesh
              name="Object_7"
              geometry={nodes.Object_7.geometry}
              material={materials["Material.002"]}
            />
          </group>
          <group
            name="Circle001_12"
            position={[0.203, 0.008, -0.104]}
            rotation={[0.011, -0.75, 1.274]}
          />
        </group>
        <mesh
          name="Object_14"
          geometry={nodes.Object_14.geometry}
          material={materials.PaletteMaterial003}
          position={[0, -0.014, 0]}
          scale={0.275}
        />
        <mesh
          name="Object_16"
          geometry={nodes.Object_16.geometry}
          material={materials.PaletteMaterial001}
          position={[0, 0.008, -0.104]}
          rotation={[1.949, 0, 0]}
          scale={0.275}
        />
        <mesh
          name="Object_21"
          geometry={nodes.Object_21.geometry}
          material={materials.PaletteMaterial004}
          position={[0, -0.014, 0]}
          scale={0.275}
        />
        <mesh
          name="Object_27"
          geometry={nodes.Object_27.geometry}
          material={materials["Touch_Bar_Shot_2021-04-02_at_18.13.28"]}
          position={[0, -0.014, 0]}
          scale={0.275}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/laptop-transformed.glb");
