/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 python.glb -T 
Files: python.glb [39.77KB] > /Users/hsuwinlatt/Desktop/Work/jsm pj/three-d-portfolio-2025/public/models/python-transformed.glb [5.15KB] (87%)
Author: Acvantad (https://sketchfab.com/Acvantad)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/python-programming-language-44d992bf56e244448e9ee5b4da083287
Title: Python Programming language
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function PythonLogo(props) {
  const { nodes, materials } = useGLTF("/models/python-transformed.glb");
  return (
    <group scale={0.7} {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.material}
        position={[-0.002, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={2.501}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials[".001"]}
        position={[-0.002, 0, 0]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={2.501}
      />
    </group>
  );
}

useGLTF.preload("/models/python-transformed.glb");
