/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 room.glb -T 
Files: room.glb [890.66KB] > /Users/hsuwinlatt/Desktop/Work/jsm pj/three-d-portfolio-2025/public/models/room-transformed.glb [89.34KB] (90%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Room(props) {
  const { nodes, materials } = useGLTF("/models/room-transformed.glb");
  const screens = useRef();

  return (
    <group {...props} dispose={null}>
      <mesh
        receiveShadow
        geometry={nodes.body1_blinn1_0001.geometry}
        material={materials["blinn1.001"]}
      />
      <mesh
        ref={screens}
        geometry={nodes.body1_blinn1_0001_1.geometry}
        material={materials["lambert1.001"]}
      />
      <mesh
        geometry={nodes.body1_blinn1_0001_2.geometry}
        material={materials["phong1.001"]}
      />
    </group>
  );
}

useGLTF.preload("/models/room-transformed.glb");
