/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 room-optimized.glb -T 
Files: room-optimized.glb [1.35MB] > /Users/hsuwinlatt/Desktop/Work/jsm pj/three-d-portfolio-2025/public/models/room-optimized-transformed.glb [114.17KB] (92%)
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { Bloom, EffectComposer } from "@react-three/postprocessing";
import { BlendFunction } from "postprocessing";

export function Model(props) {
  const { nodes, materials } = useGLTF(
    "/models/room-optimized-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        receiveShadow
        geometry={nodes.body1_blinn1_0_1.geometry}
        material={materials.blinn1}
      />
      {/* <EffectComposer>
        <Bloom
          intensity={1.5} // Strength of the bloom
          luminanceThreshold={0.2} // Minimum luminance needed
          luminanceSmoothing={0.9} // Smooth transition
          blendFunction={BlendFunction.ADD} // How it blends
        />
      </EffectComposer> */}
      <mesh
        geometry={nodes.body1_blinn1_0_2.geometry}
        material={materials.lambert1}
      />
      <mesh
        geometry={nodes.body1_blinn1_0_3.geometry}
        material={materials.phong1}
      />
    </group>
  );
}

useGLTF.preload("/models/room-optimized-transformed.glb");
