/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 threejs.glb -T 
Files: threejs.glb [19.03KB] > /Users/hsuwinlatt/Desktop/Work/jsm pj/three-d-portfolio-2025/public/models/threejs-transformed.glb [2.48KB] (87%)
Author: Fyrestar (https://sketchfab.com/mevedia)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/threejs-60320862bf904b7ab0e032c27daf7c7c
Title: Three.js
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function ThreejsLogo(props) {
  const { nodes, materials } = useGLTF("/models/threejs-transformed.glb");

  return (
    <group {...props} dispose={null}>
      <mesh
        scale={0.05}
        geometry={nodes.Object_5.geometry}
        material={materials.material_0}
      />
    </group>
  );
}

useGLTF.preload("/models/threejs-transformed.glb");
